### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by BuckoA511** [tebl/C64-Lumafix#1]
Hi, I'm Matt from VideoGamePerfection.com. We're looking to start selling the LumaFix to our customers as part of our C64 refurbishment services. Can we use the schematics here to make boards up and do this? I would be happy to pay royalties to whomever owns the rights.

Thank you for your time.

**Comment by tebl** [comment]
I don't have an overview of who owns the rights as it is works based upon works, but I would not object to the use of my version of the designs in this way and would be happy to see it used.
